### PR TITLE
hu typos

### PR DESCRIPTION
**Pull request by ovari**
Sorry, also need to fix:
https://addons.thunderbird.net/hu/thunderbird/addon/grammar-checker/

### CODE REVIEW

**Comment by nuald** [comment]
Please let me know if you'd like me to release a new minor version of the add-on.

**Comment by ovari** [comment]
If you could please release a new minor version of the add-on it would be appreciated as the title was also incorrect. The Hungarian title had a mistake that is similar to, in English, `Grammer Checker` instead of `Grammar Checker`. Considering what the add-on does, it isn't good to have a grammar (or spelling) mistake in the title. What do you think? Thank you once again

**Comment by ovari** [comment]
It would be appreciated if you could also fix the hu typos at ATN.
https://addons.thunderbird.net/hu/thunderbird/addon/grammar-checker/
a) Title:
`Nyelvtan-ellenőrzes (Grammar Checker)`
→
`Nyelvtan-ellenőrzés (Grammar Checker)`
b) Summary:
`Nyelvtan-ellenőrzes a LanguageTool segítségével.`
→
`Nyelvtan-ellenőrzés a „LanguageTool” segítségével`
c) Caption:
`Nyelvtan-ellenőrzes beállítások`
→
`Nyelvtan-ellenőrzés beállítások`

**Comment by nuald** [comment]
Descriptions have been updated, and the new version (0.8.4) of the add-on has been approved and is available now for download.

**Comment by ovari** [comment]
Thank you

**Pull request merged**
